# @package _global_

batch_size: 48
num_workers: 8

model:
  mot_checkpoint_mixed_attn: false

lr_scheduler_type: "cosine"
learning_rate: 5.0e-5
num_epochs: 1
max_steps: null
log_every: 1
save_every: 2000
eval_every: 0

gradient_accumulation_steps: 1
weight_decay: 5.0e-3
resume: null
